FROM jupyter/datascience-notebook:latest

# Switch to root to install additional packages
RUN pip install --no-cache-dir \
	langchain \
	langchain-community \
	qdrant-client \
	pydantic \
	mlflow \
	ollama
