FROM jupyter/datascience-notebook:latest

# Switch to root to install additional packages
RUN pip install --no-cache-dir \
	langchain \
	devtools \
	langchain-ollama \
	langchain-qdrant \
	qdrant-client \
	langchain-text-splitters \
	dotenv \
	pydantic \
	mlflow \
	ollama
