name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  # Allow manual workflow dispatch
  workflow_dispatch:
# Discover and build for all Dockerfile-containing directories
jobs:
  discover:
    name: Discover image directories
    runs-on: omen
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: set-matrix
        name: Set image matrix
        run: |
          # Find directories with Dockerfile
          dirs=$(find . -maxdepth 2 -type f -name Dockerfile -printf '%h\n' | sed 's|^\./||' | sort -u)
          # Build JSON include entries
          entries=$(printf '%s\n' "$dirs" | awk '{printf "{\"path\":\"%s\"},", $0}' | sed 's/,$//')
          echo "matrix={\"include\":[${entries}]}" >> $GITHUB_OUTPUT
  build_and_publish:
    needs: discover
    # Allow writing to packages registry for GHCR push
    permissions:
      contents: read
      packages: write
    runs-on: omen
    strategy:
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image for ${{ matrix.path }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jupyter-images:${{ matrix.path }}
            ghcr.io/${{ github.repository_owner }}/jupyter-images:${{ matrix.path }}-${{ github.sha }}
